### ISSUE TITLE
Determining where is the app installed

### ISSUE THREAD

**Issue by akrishnakumar-splunk** [sbhimani-splunk/pre-checks#6]
Here, I would like to bring you this notice that the script shows whether it is installed or not but it does not really shows in which search head it is installed on. There might be a case that the SRE might want to install it on ES search head, but there's no way to determine whether it is installed over there or not

**Comment by sbhimani-splunk** [comment]
Hey @akrishnakumar-splunk,
We will get the installed app information from the DMC search-head. So for other search-head, we need to manually check.
