### ISSUE TITLE
Script taking wrong app folder

### ISSUE THREAD

**Issue by kbarapatre-splunk** [sbhimani-splunk/pre-checks#8]
During the checks of dependent apps, script has taken wrong app folder.

For example 

App 1274, Dependent Apps : 1876|2882

So for pre-checks of 1876 and 2882 it has taken app folder of app 1274. Here is script output

*+Pre-checks for 1274 v5.1.1+*
 - 1sot:  1274_5.1.1.tgz
 - APPCERT:  APPCERT-11284, status: Closed, resolution:  Fixed
 - Splunk-Base: available
 - Supported Splunk versions:  7.0, 6.6, 6.5
 - self-service installation: No
 - App directory name:  splunk_app_aws
 - *The app 1274 is already installed on adhoc SH with 4.2.0 version.*
 - need Splunk restart after upgrade: False
 - APP DETAILS
	App-ID:  1274
	can be installed on: sh 
	dependent apps:  1876|2882
 - APP DETAILS for dependent app  1876
	App-ID:  1876
	can be installed on: sh 
	latest version: 4.5.0
	Splunk-Base: available
	Supported Splunk versions:  7.1, 7.0, 6.6, 6.5
	1sot:  1876_4.5.0.tgz
	self-service installation: No
	App directory name:  splunk_app_aws
	*The app 1876 is already installed on adhoc SH with 4.2.0 version.*
	need Splunk restart after upgrade: False
	APPCERT:  APPCERT-10850, status: Closed, resolution:  Fixed
 - APP DETAILS for dependent app  2882
	App-ID:  2882
	can be installed on: sh 
	latest version: 1.2
	Splunk-Base: available
	Supported Splunk versions:  7.1, 7.0, 6.6, 6.5, 6.4
	1sot:  2882_1.2.tgz
	self-service installation: No
	App directory name:  splunk_app_aws
	*The app 2882 is already installed on adhoc SH with 4.2.0 version.*
	need Splunk restart after upgrade: False
	APPCERT:  APPCERT-2190, status: Closed, resolution:  Fixed

Please check this

**Comment by akrishnakumar-splunk** [comment]
This issue has been resolved. Can we close this?
